### ISSUE TITLE
Road to 4.0

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#409]
Currently the iOS client is getting a rewrite which happens on [develop](https://github.com/criticalmaps/criticalmaps-ios/tree/develop)

This list should give an overview of what features are in progress and what is still to do. 

#SwiftUI #TCA

- [x] #426 
- [x] #422

- [x] Add rules feature #414 

- [x] Add settings #415
  - [x] App theme
  - [x] Ride event settings
  - [x] Observation mode
  - ~~Banners and info~~

- [x] Add infobanner component for next ride event -> #410 
- [x] Add global error state to be able to present error messages

- [x] Snapshot tests for views and components

- [x] Some kind of navigation handling with SwiftUI. There are some candidates but decision is not yet final... #412

- [x]  #421 

- [ ] #143 

- [x] #245
 
- [ ] #127 

- [x] #423

- [x] #424

- [ ] #427

**Comment by mltbnz** [comment]
closing it since the rebuild got merged #429
